# name: GitHub - Activity - Readme
# on:
#   schedule:
#     - cron: "*/30 * * * *"
#   workflow_dispatch:
# jobs:
#   build:
#     name: Update this repo's README with recent activity
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write

#     steps:
#       - uses: actions/checkout@v3
#       - uses: jamesgeorge007/github-activity-readme@v0.4.4
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           COMMIT_MSG: "âš¡ Update README with the recent activity"
#           MAX_LINES: 10
#           COMMIT_NAME: GitHub Activity Readme
